[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Cache-Control = "no-store"
        Expect-CT = "max-age=86400, enforce"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''

        Permissions-Policy = '''
            interest-cohort=(none)
        '''

    
