[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Expect-CT = "max-age=86400, enforce"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "require-corp"
        Access-Control-Allow-Origin = "https://numerale.netlify.app"
        
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''
        Permissions-Policy = '''
            camera=(), 
            microphone=(), 
            geolocation=(),
            accelerometer=(),
            battery=(),
            document-domain=(),
            gyroscope=(),
            magnetometer=(),
            usb=()
        '''
        Content-Security-Policy = '''
            script-src 'https:' 'unsafe-inline' 'self';
            navigate-to 'none';
            form-action 'none';
            media-src 'none';
            object-src 'none';
        '''
