[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Content-Type = "text/html; charset=UTF-8"
        Expect-CT = "max-age=86400, enforce"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "require-corp"
        Access-Control-Allow-Origin = "https://numerale.netlify.app"
        
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''

        Permissions-Policy = '''
            interest-cohort=(none)
        '''

    
