[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Expect-CT = "max-age=86400, enforce"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "require-corp"
        Access-Control-Allow-Origin = "https://numerale.netlify.app"
        X-Forwarded-Proto = "https"
        X-Permitted-Cross-Domain-Policies = "none"
        
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''
        
        Permissions-Policy= '''
            accelerometer=(), 
            ambient-light-sensor=(), 
            autoplay=(), 
            battery=(), 
            camera=(), 
            display-capture=(), 
            document-domain=(), 
            encrypted-media=(), 
            execution-while-out-of-viewport=(), 
            fullscreen=(), 
            geolocation=(), 
            gyroscope=(), 
            keyboard-map=(), 
            magnetometer=(), 
            microphone=(), 
            midi=(), 
            navigation-override=(), 
            payment=(), 
            picture-in-picture=(), 
            publickey-credentials-get=(), 
            screen-wake-lock=(), 
            sync-xhr=(), 
            usb=(), 
            web-share=(), 
            xr-spatial-tracking=()
        '''
        
        Content-Security-Policy = '''
            script-src * 'unsafe-inline' 'unsafe-eval';
            navigate-to 'none';
            form-action 'none';
            media-src 'none';
            object-src 'none';
        '''
